// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Cache struct {
	Key   string        `json:"key"`
	Value string        `json:"value"`
	Ttl   sql.NullInt32 `json:"ttl"`
}
